version: '2'
services:
  app:
    build:
      context: ./docker
      dockerfile: Dockerfile
    image: melyo/laravel-docker-playground
    volumes:
      - ./blog/:/var/www/blog/
    networks:
      - app-network
  nginx:
    image: nginx:1.12-alpine
    volumes:
      - ./blog/:/var/www/blog/
      - ./docker/default:/etc/nginx/conf.d/default.conf
    ports:
      - 8011:8011
    networks:
      - app-network
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - app-network
  redis:
    image: redis:4.0-alpine
    volumes:
      - redisdata:/data
    networks:
      - app-network
volumes:
  mysqldata:
    driver: "local"
  redisdata:
    driver: "local"
networks:
  app-network:
    driver: "bridge"
